name: Create Team
description: Action to create a team in Terraform Cloud
inputs:
  terraform_token:
    description: 'Terraform Cloud API Token'
    required: true
  organization:
    description: 'Terraform Cloud Organization'
    required: true
  team_name:
    description: 'Name of the team to create'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Crear Equipo
      shell: bash
      run: |
        curl \
              --header "Authorization: Bearer ${{ inputs.terraform_token }}" \
              --header "Content-Type: application/vnd.api+json" \
              --request POST \
              --data '{
              "data": {
                "type": "teams",
                "attributes": {
                    "name": "${{ inputs.team_name }}"
                }
                }
              }
              }' \
              https://app.terraform.io/api/v2/organizations/${{ inputs.organization }}/teams
