name: Create Project
description: Action to create a project in Terraform Cloud
inputs:
  terraform_token:
    description: 'Terraform Cloud API Token'
    required: true
  organization:
    description: 'Terraform Cloud Organization'
    required: true
  project_name:
    description: 'Name of the project to create'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Crear Proyecto
      shell: bash
      run: |
        curl \
          --header "Authorization: Bearer ${{ inputs.terraform_token }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data '{
            "data": {
              "type": "projects",
              "attributes": {
                "name": "${{ inputs.project_name }}",
                "description": "Proyecto creado automáticamente desde GitHub Actions"
              }
            }
          }' \
          https://app.terraform.io/api/v2/organizations/${{ inputs.organization }}/projects
