name: Dispatch Workflow

on:
        push:
          branches:
            - main  #
 


jobs:
  trigger_orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Orchestrator Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const inputs = {
              project_name: 'IAAC',
              team_name: 'PILOTO',
              user_email: 'loayzaascatea@gmail.com'
            };
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'onboarding_tfc_cloud.yml',
              ref: "main",
              inputs: inputs
            });
        env:
         GITHUB_TOKEN: ${{ secrets.PAT }}