name: Workflow

on:
  push:
      branches:
            - main  # Rama desde donde se dispara
jobs:
  trigger_orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Orchestrator Workflow
        uses: actions/github-script@v4
        with:
          script: |
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'onboarding_tfc_cloud.yml',
              ref: "main", // Rama desde donde se dispara
              inputs: {
                project_name: 'BADI',
                team_name: 'BADI',
                user_email: 'aascatem@gmail.com'
                }
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}