name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Nombre del proyecto a crear'
        required: true
        type: string
      team_name:
        description: 'Nombre del equipo a crear'
        required: true
        type: string
      user_email:
        description: 'Correo electrónico del usuario a invitar'
        required: true
        type: string



jobs:
  trigger_orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Orchestrator Workflow
        uses: actions/github-script@v4
        with:
          script: |
            const inputs = {
              project_name: '${{ github.event.inputs.project_name }}',
              team_name: '${{ github.event.inputs.team_name }}',
              user_email: '${{ github.event.inputs.user_email }}'
            };
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'onboarding_tfc_cloud.yml',
              ref: context.ref,
              inputs: inputs
            });