# This is a basic workflow to help you get started with Actions
name: Orchestrator Workflow

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      team_name:
        required: true
        type: string
      user_email:
        required: true
        type: string
    secrets:
      TERRAFORM_CLOUD_TOKEN:
        required: true

jobs:
  create_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Verify Inputs
        run: |
          echo "Project Name: ${{ inputs.project_name }}"
          echo "Team Name: ${{ inputs.team_name }}"
          echo "User Email: ${{ inputs.user_email }}"

      - name: Crear Proyecto en Terraform Cloud
        uses: ./actions/create_project
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          project_name: ${{ inputs.project_name }}

  create_team:
    runs-on: ubuntu-latest
    needs: create_project
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Crear Equipo en Terraform Cloud
        uses: ./actions/create_team
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          team_name: ${{ inputs.team_name }}

  invite_user:
    runs-on: ubuntu-latest
    needs: create_team
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Invitar Usuario a la Organización
        uses: ./actions/invite_user
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          user_email: ${{ inputs.user_email }}

