name: Orchestrator Workflow

on:
  workflow_dispatch:
    inputs:
      project_name:
        required: true
        type: string
      team_name:
        required: true
        type: string
      user_email:
        required: true
        type: string

jobs:
  create_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Crear Proyecto en Terraform Cloud
        uses: ./actions/create_project
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLUOD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          project_name: ${{ inputs.project_name }}
          
  create_team:
    runs-on: ubuntu-latest
    needs: create_project
    steps:
      - name: Crear Equipo en Terraform Cloud
        uses: ./actions/create_team
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLUOD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          team_name: ${{ inputs.team_name }}
          user_email: ${{ inputs.user_email }}

  invite_user:
    runs-on: ubuntu-latest
    needs: create_team
    steps:
      - name: Invitar Usuario a Terraform Cloud
        uses: ./actions/invite_user
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLUOD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          team_name: ${{ inputs.team_name }}
          user_email: ${{ inputs.user_email }}