name: Orchestrator Workflow

on:
  push:
    branches:
      - main  # Especifica la rama en la que deseas que se dispare el workflow

jobs:
  create_project:
    runs-on: ubuntu-latest
    steps:
      - name: Crear Proyecto en Terraform Cloud
        uses: ./actions/create_project
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLUD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          project_name: 'IAAC'
          
  create_team:
    runs-on: ubuntu-latest
    steps:
      - name: Crear Equipo en Terraform Cloud
        uses: ./actions/create_team
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLUD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          team_name: 'PILOTO'
          user_email: 'loayzaascatea@gmail.com'

  invite_user:
    runs-on: ubuntu-latest
    needs: create_team
    steps:
      - name: Invitar Usuario a Terraform Cloud
        uses: ./actions/invite_user
        with:
          terraform_token: ${{ secrets.TERRAFORM_CLUD_TOKEN }}
          organization: "CODELIKE-CLOUD"
          team_name: 'PILOTO'
          user_email: 'loayzaascatea@gmail.com'